### ISSUE TITLE
Importance score evaluation framework

### ISSUE THREAD

**Issue by zouying-sjtu** [mayu-ot/rethinking-evs#1]
could you please release the code to generate Table2. Kendall’s τ and Spearman’s ρ correlation coefficients. 
i find just got 0.24 instead of 0.204 for Spearman’s ρ on Human annotation.
Thanks

**Comment by mayu-ot** [comment]
I uploaded "notebooks/rank order statistics.ipynb". Please check the script.
Note that the correlations are evaluated in a leave-one-out manner.
Please check so that your code does not compare each human annotation to all human annotations including the target annotation itself.
